# Generated by Django 4.1.1 on 2022-09-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='familia',
        ),
    ]
